python prepare_retrieval_data.py \
    --retrieval_type sparse \
    --tokenizer_name gpt2 \
    --max_length 1024 \
    --dataset_path wikitext \
    --dataset_name wikitext-103-v1 \
    --dataset_split test \
    --index_name wikipedia-dpr \
    --forbidden_titles_path ralm/retrievers/wikitext103_forbidden_titles.txt \
    --stride 4 \
    --output_file logs/bm25_retrieval \
    --num_tokens_for_query 32 \
    --num_docs 16 
