python3 -m cbralm.bm25_retrieval \
    --project-name 'wikitext_rql_32_rs_4_topK_100' \
    --data-dir '' \
    --retrieval-corpus 'wikipedia-dpr-100w' \
    --query-corpus 'wikitext' \
    --forbidden-titles 'wikitext_forbidden_titles.txt' \
    --tokenizer 'gpt2' \
    --retrieval-query-length 32 \
    --retrieval-stride 4 \
    --max-length 1024 \
    --topK 100 \
