python summarize_results.py \
    --benchmark-dir ./benchmark \
    --sub-group bm25_retrieval_gpt2_colbert_rerank_layer bm25_retrieval_bert_based_uncased_colbert_rerank_gpt2_layer\
    --layer-lower 0 \
    --layer-upper 11 \
    --baseline baseline \
    --random bm25_random \
    --first bm25 \
    --oracle bm25_oracle \
    --retriever bm25 \
    --reranker gpt2 \
    --strategy colbert-embedding \
    --plot-type plot \
    --plot-style ticks \
    --plot-targets first \
    --plot-name 'GPT2 vs. Bert' \
    --plot-save gpt2vBert
