python summarize_results.py \
    --benchmark-dir ./benchmark \
    --sub-group bm25_retrieval_gpt2_colbert_rerank_gpt2_medium_layer \
    --layer-lower 0 \
    --layer-upper 35 \
    --baseline baseline \
    --random bm25_random_medium \
    --first bm25_first_medium \
    --oracle bm25_oracle \
    --retriever bm25 \
    --reranker gpt2 \
    --strategy colbert-embedding \
    --plot-type plot \
    --plot-style ticks \
    --plot-targets first \
    --indicate-best \
    --plot-name 'GPT2 Medium' \
    --plot-save gpt2_small_medium
